# Change these first
owner: 313326 # Your GitHub organization or username, where this repository lives
repo: monitor # The name of this repository

sites:
  - name: Short Url Frontend
    url: https://link.313326.xyz/
  - name: Short Url Backend
    url: https://l.313326.xyz/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: monitor.313326.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://link.313326.xyz/313326.xyz-logo/vector/default.svg
  favicon: https://link.313326.xyz/favicon_io/favicon-32x32.png
  theme: ocean
  name: 313326 Monitoring
  introTitle: "**313326 Monitoring** เป็นระบบตรวจสอบการออนไลน์และแสดงสถานะ"
  introMessage: นี่คือหน้าแสดงสถานะที่ใช้ข้อมูล **เรียลไทม์** จาก [repository GitHub ของเรา](https://github.com/313326/monitoring)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
